# Generated by Django 3.1.7 on 2021-04-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('sequence', models.IntegerField(default=0)),
                ('pnp', models.BooleanField()),
                ('label', models.CharField(choices=[('Today', 'Today'), ('Specify', 'Specify'), ('Compare', 'Compare')], max_length=8)),
                ('data', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('date1', models.CharField(max_length=15)),
                ('resultdata', models.ForeignKey(db_column='resultdata_id', on_delete=django.db.models.deletion.CASCADE, to='survey.resultdata')),
            ],
        ),
        migrations.CreateModel(
            name='Specify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('date1', models.CharField(max_length=15)),
                ('date2', models.CharField(max_length=15)),
                ('resultdata', models.ForeignKey(db_column='resultdata_id', on_delete=django.db.models.deletion.CASCADE, to='survey.resultdata')),
            ],
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('date1', models.CharField(max_length=15)),
                ('date2', models.CharField(max_length=15)),
                ('date3', models.CharField(max_length=15)),
                ('date4', models.CharField(max_length=15)),
                ('resultdata', models.ForeignKey(db_column='resultdata_id', on_delete=django.db.models.deletion.CASCADE, to='survey.resultdata')),
            ],
        ),
    ]
