# Generated by Django 3.2 on 2021-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_stepcountdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdata',
            name='q_dsc',
            field=models.CharField(default='db_index_dsc', max_length=50),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='data',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='pid',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='pnp',
            field=models.BooleanField(default=False),
        ),
    ]
