# Generated by Django 3.2 on 2021-07-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210531_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='data',
            field=models.TextField(),
        ),
    ]
