# Generated by Django 3.2 on 2021-08-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_resultdata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='date3',
        ),
        migrations.RemoveField(
            model_name='compare',
            name='date4',
        ),
        migrations.RemoveField(
            model_name='specify',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='specify',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='today',
            name='date1',
        ),
        migrations.AddField(
            model_name='compare',
            name='query',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='checked',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='end_date_1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='end_date_2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='start_date_1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='start_date_2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='survey_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='specify',
            name='query',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='today',
            name='query',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_num', models.CharField(max_length=15)),
                ('resultdata', models.ForeignKey(db_column='resultdata_id', on_delete=django.db.models.deletion.CASCADE, to='survey.resultdata')),
            ],
        ),
    ]
